spring:
  profile: dev
  h2:
    console:
      enabled: 'true'
  datasource:
    username: sa
    url: jdbc:mariadb://localhost:3306/java_blog
    driverClassName: org.mariadb.jdbc.Driver
    password: password
  jpa:
    # database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: 'true'
debug: 'true'
welcome:
  message: welcome to my first API in Java
server:
  port: '8080'
