spring:
  profile: dev
  h2:
    console:
      enabled: 'true'
  datasource:
    username: root
    url: jdbc:mariadb://localhost:3306/java_blog
    driverClassName: org.mariadb.jdbc.Driver
    password: root
  jpa:
    # database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: 'true'
debug: 'true'
welcome:
  message: welcome to my first API in Java

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env, beans"

server:
  port: '8080'
